import { Component, inject } from '@angular/core';
import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { CustomerAccountDataApiService, CustomerAddress, CustomerAttributes } from '../../core/customer/customer-account-data-api.service';

@Component({ standalone: true, imports: [ReactiveFormsModule, RouterLink], styleUrls: ['../../auth/auth-page.scss'], template: `
<div class="account-page"><div class="eyebrow">Customer / Settings</div><h1>Details that travel.</h1><div class="account-grid">
<section class="auth-panel"><h2>Address book</h2>@for (address of addresses; track address.id) { <div class="security-block"><strong>{{ address.firstName }} {{ address.lastName }}</strong><span>{{ address.address1 }}, {{ address.city }}, {{ address.countryCode }}</span><button class="account-action" (click)="edit(address)">Edit</button><button class="account-action" (click)="remove(address.id)">Delete</button></div> } @empty { <p class="profile-note">No saved addresses.</p> }<form [formGroup]="addressForm" (ngSubmit)="saveAddress()"><div class="field"><label>First name</label><input formControlName="firstName"></div><div class="field"><label>Last name</label><input formControlName="lastName"></div><div class="field"><label>Address</label><input formControlName="address1"></div><div class="field"><label>City</label><input formControlName="city"></div><div class="field"><label>Country code</label><input formControlName="countryCode" maxlength="2"></div><div class="field"><label>Phone</label><input formControlName="phoneNumber"></div><label><input type="checkbox" formControlName="isDefault"> Default address</label><button class="submit">{{ editingId ? 'Update address' : 'Add address' }}</button></form></section>
<section class="auth-panel"><h2>Preferences</h2><form [formGroup]="attributesForm" (ngSubmit)="saveAttributes()">@for (definition of attributes?.definitions ?? []; track definition.systemName) { <div class="field"><label>{{ definition.name }}</label>@if (definition.dataType === 'boolean') { <select [formControlName]="definition.systemName"><option value="false">No</option><option value="true">Yes</option></select> } @else { <input [formControlName]="definition.systemName"> }</div> }<button class="submit">Save preferences</button></form><div class="security-block"><h2>Change email</h2><form [formGroup]="emailForm" (ngSubmit)="requestEmailChange()"><div class="field"><label>New email</label><input type="email" formControlName="newEmail"></div><div class="field"><label>Current password</label><input type="password" formControlName="currentPassword"></div><button class="submit">Send confirmation link</button></form></div>@if(message){<div class="form-success">{{message}}</div>}@if(error){<div class="form-error">{{error}}</div>}<div class="auth-links"><a routerLink="/customer/profile">Back to profile</a></div></section>
</div></div>`, styles: [`.account-page{max-width:1050px;margin:0 auto;padding:2rem 0 5rem}.eyebrow{color:var(--green);font:700 .72rem/1 var(--mono-font);letter-spacing:.13em;text-transform:uppercase}h1{margin:1rem 0 2.5rem;font:700 clamp(3rem,7vw,6.5rem)/.94 var(--display-font)}.account-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.security-block{display:grid;gap:.55rem;margin-top:1.25rem;padding-top:1rem;border-top:1px solid var(--line)}.security-block .account-action{width:max-content;border:1px solid var(--line-strong);padding:.5rem .75rem;background:transparent;color:var(--green);font:700 .72rem var(--mono-font);cursor:pointer}.security-block .account-action:hover{background:var(--green);color:var(--paper);border-color:var(--green)}select{width:100%;padding:.8rem;border:1px solid var(--line-strong);background:var(--paper);font:inherit}.profile-note{color:var(--muted)}@media(max-width:760px){.account-grid{grid-template-columns:1fr}}`] })
export class AccountDataPage { private readonly api=inject(CustomerAccountDataApiService); private readonly fb=inject(NonNullableFormBuilder); addresses:CustomerAddress[]=[]; attributes?:CustomerAttributes; editingId=0; message=''; error=''; readonly addressForm=this.fb.group({firstName:['',Validators.required],lastName:['',Validators.required],address1:['',Validators.required],city:['',Validators.required],countryCode:['VN',Validators.required],phoneNumber:['',Validators.required],isDefault:[false]}); readonly attributesForm=this.fb.group({}); readonly emailForm=this.fb.group({newEmail:['',[Validators.required,Validators.email]],currentPassword:['',Validators.required]}); constructor(){this.load();} load(){this.api.addresses().subscribe(x=>this.addresses=x);this.api.attributes().subscribe(x=>{this.attributes=x;for(const d of x.definitions)this.attributesForm.addControl(d.systemName,this.fb.control(x.values[d.systemName]??(d.dataType==='boolean'?'false':'')));});} edit(a:CustomerAddress){this.editingId=a.id;this.addressForm.patchValue(a);} saveAddress(){if(this.addressForm.invalid)return;this.api.saveAddress({...this.addressForm.getRawValue(),id:this.editingId}).subscribe({next:()=>{this.editingId=0;this.addressForm.reset({countryCode:'VN',isDefault:false});this.load();},error:()=>this.error='Unable to save address.'});} remove(id:number){this.api.deleteAddress(id).subscribe(()=>this.load());} saveAttributes(){this.api.saveAttributes(this.attributesForm.getRawValue()).subscribe({next:()=>this.message='Preferences saved.',error:()=>this.error='Unable to save preferences.'});} requestEmailChange(){if(this.emailForm.invalid)return;const v=this.emailForm.getRawValue();this.api.requestEmailChange(v.newEmail,v.currentPassword).subscribe({next:()=>this.message='Check the new email address and open its confirmation link.',error:()=>this.error='Unable to request email change.'});} }
