import { Component, inject } from '@angular/core';
import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { TranslocoDirective, TranslocoService } from '@jsverse/transloco';
import { CustomerAccountDataApiService, CustomerAddress, CustomerAttributeDefinition, CustomerAttributes } from '../../core/customer/customer-account-data-api.service';

@Component({ standalone: true, imports: [ReactiveFormsModule, RouterLink, TranslocoDirective], styleUrls: ['../../auth/auth-page.scss'], template: `
<div class="account-page" *transloco="let t"><div class="eyebrow">{{ t('customer.settings.eyebrow') }}</div><h1>{{ t('customer.settings.title') }}</h1><div class="account-grid">
<section class="auth-panel"><h2>{{ t('customer.settings.addressBook') }}</h2>@for (address of addresses; track address.id) { <div class="security-block"><strong>{{ address.firstName }} {{ address.lastName }}</strong><span>{{ address.address1 }}, {{ address.city }}, {{ address.countryCode }}</span><button class="account-action" (click)="edit(address)">{{ t('customer.settings.edit') }}</button><button class="account-action" (click)="remove(address.id)">{{ t('customer.settings.delete') }}</button></div> } @empty { <p class="profile-note">{{ t('customer.settings.noAddresses') }}</p> }<form [formGroup]="addressForm" (ngSubmit)="saveAddress()"><div class="field"><label>{{ t('customer.fields.firstName') }}</label><input formControlName="firstName"></div><div class="field"><label>{{ t('customer.fields.lastName') }}</label><input formControlName="lastName"></div><div class="field"><label>{{ t('customer.fields.address') }}</label><input formControlName="address1"></div><div class="field"><label>{{ t('customer.fields.city') }}</label><input formControlName="city"></div><div class="field"><label>{{ t('customer.fields.countryCode') }}</label><input formControlName="countryCode" maxlength="2"></div><div class="field"><label>{{ t('customer.fields.phone') }}</label><input formControlName="phoneNumber"></div><label><input type="checkbox" formControlName="isDefault"> {{ t('customer.settings.defaultAddress') }}</label><button class="submit">{{ editingId ? t('customer.settings.updateAddress') : t('customer.settings.addAddress') }}</button></form></section>
<section class="auth-panel"><h2>{{ t('customer.settings.preferences') }}</h2><form [formGroup]="attributesForm" (ngSubmit)="saveAttributes()">@for (definition of attributes?.definitions ?? []; track definition.systemName) { <div class="field"><label>{{ attributeLabel(definition) }}</label>@if (definition.dataType === 'boolean') { <select [formControlName]="definition.systemName"><option value="false">{{ t('customer.settings.no') }}</option><option value="true">{{ t('customer.settings.yes') }}</option></select> } @else { <input [formControlName]="definition.systemName"> }</div> }<button class="submit">{{ t('customer.settings.savePreferences') }}</button></form><div class="security-block"><h2>{{ t('customer.settings.changeEmail') }}</h2><form [formGroup]="emailForm" (ngSubmit)="requestEmailChange()"><div class="field"><label>{{ t('customer.settings.newEmail') }}</label><input type="email" formControlName="newEmail"></div><div class="field"><label>{{ t('customer.settings.currentPassword') }}</label><input type="password" formControlName="currentPassword"></div><button class="submit">{{ t('customer.settings.sendConfirmation') }}</button></form></div>@if(message){<div class="form-success">{{ t(message) }}</div>}@if(error){<div class="form-error">{{ t(error) }}</div>}<div class="auth-links"><a routerLink="/customer/profile">{{ t('customer.links.backToProfile') }}</a></div></section>
</div></div>`, styles: [`.account-page{max-width:1050px;margin:0 auto;padding:2rem 0 5rem}.eyebrow{color:var(--green);font:700 .72rem/1 var(--mono-font);letter-spacing:.13em;text-transform:uppercase}h1{margin:1rem 0 2.5rem;font:700 clamp(3rem,7vw,6.5rem)/.94 var(--display-font)}.account-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.security-block{display:grid;gap:.55rem;margin-top:1.25rem;padding-top:1rem;border-top:1px solid var(--line)}.security-block .account-action{width:max-content;border:1px solid var(--line-strong);padding:.5rem .75rem;background:transparent;color:var(--green);font:700 .72rem var(--mono-font);cursor:pointer}.security-block .account-action:hover{background:var(--green);color:var(--paper);border-color:var(--green)}select{width:100%;padding:.8rem;border:1px solid var(--line-strong);background:var(--paper);font:inherit}.profile-note{color:var(--muted)}@media(max-width:760px){.account-grid{grid-template-columns:1fr}}`] })
export class AccountDataPage { private readonly transloco=inject(TranslocoService);
  /** Known attributes have a translation keyed by systemName; new ones fall back to the name from the API. */
  attributeLabel(definition:CustomerAttributeDefinition){const key=`customer.settings.attributes.${definition.systemName}`;const text=this.transloco.translate(key);return text===key?definition.name:text;}
  private readonly api=inject(CustomerAccountDataApiService); private readonly fb=inject(NonNullableFormBuilder); addresses:CustomerAddress[]=[]; attributes?:CustomerAttributes; editingId=0; message=''; error=''; readonly addressForm=this.fb.group({firstName:['',Validators.required],lastName:['',Validators.required],address1:['',Validators.required],city:['',Validators.required],countryCode:['VN',Validators.required],phoneNumber:['',Validators.required],isDefault:[false]}); readonly attributesForm=this.fb.group({}); readonly emailForm=this.fb.group({newEmail:['',[Validators.required,Validators.email]],currentPassword:['',Validators.required]}); constructor(){this.load();} load(){this.api.addresses().subscribe(x=>this.addresses=x);this.api.attributes().subscribe(x=>{this.attributes=x;for(const d of x.definitions)this.attributesForm.addControl(d.systemName,this.fb.control(x.values[d.systemName]??(d.dataType==='boolean'?'false':'')));});} edit(a:CustomerAddress){this.editingId=a.id;this.addressForm.patchValue(a);} saveAddress(){if(this.addressForm.invalid)return;this.api.saveAddress({...this.addressForm.getRawValue(),id:this.editingId}).subscribe({next:()=>{this.editingId=0;this.addressForm.reset({countryCode:'VN',isDefault:false});this.load();},error:()=>this.error='customer.settings.errors.saveAddress'});} remove(id:number){this.api.deleteAddress(id).subscribe(()=>this.load());} saveAttributes(){this.api.saveAttributes(this.attributesForm.getRawValue()).subscribe({next:()=>this.message='customer.settings.preferencesSaved',error:()=>this.error='customer.settings.errors.savePreferences'});} requestEmailChange(){if(this.emailForm.invalid)return;const v=this.emailForm.getRawValue();this.api.requestEmailChange(v.newEmail,v.currentPassword).subscribe({next:()=>this.message='customer.settings.emailChangeSent',error:()=>this.error='customer.settings.errors.emailChange'});} }
